manifest:
  remotes:
    - name: dxmh
      url-base: https://github.com/dxmh
  projects:
    - name: zmk
      remote: dxmh
      revision: jd79653
      import: app/west.yml
  self:
    path: config
